class QueryHandler:
    _query_data = {
        "amharic grade 1 amharic text book": [47],
        "amharic grade 1 amharic reference": [],
        "amharic grade 1 amharic teachers guide": [269],
        "amharic grade 1 amharic question": [],
        "amharic grade 1 english text book": [48],
        "amharic grade 1 english reference": [],
        "amharic grade 1 english teachers guide": [272],
        "amharic grade 1 english question": [],
        "amharic grade 1 math text book": [49],
        "amharic grade 1 math reference": [],
        "amharic grade 1 math teachers guide": [274],
        "amharic grade 1 math question": [],
        "amharic grade 1 science text book": [46],
        "amharic grade 1 science reference": [],
        "amharic grade 1 science teachers guide": [276],
        "amharic grade 1 science question": [],
        "amharic grade 1 art text book": [50],
        "amharic grade 1 art reference": [],
        "amharic grade 1 art teachers guide": [275],
        "amharic grade 1 art question": [],
        "amharic grade 1 health text book": [51],
        "amharic grade 1 health reference": [],
        "amharic grade 1 health teachers guide": [270],
        "amharic grade 1 health question": [],
        "amharic grade 1 moral text book": [472],
        "amharic grade 1 moral reference": [],
        "amharic grade 1 moral teachers guide": [],
        "amharic grade 1 moral question": [],
        "amharic grade 2 amharic text book": [66],
        "amharic grade 2 amharic reference": [],
        "amharic grade 2 amharic teachers guide": [],
        "amharic grade 2 amharic question": [],
        "amharic grade 2 english text book": [67],
        "amharic grade 2 english reference": [],
        "amharic grade 2 english teachers guide": [285],
        "amharic grade 2 english question": [],
        "amharic grade 2 math text book": [69],
        "amharic grade 2 math reference": [],
        "amharic grade 2 math teachers guide": [286],
        "amharic grade 2 math question": [],
        "amharic grade 2 science text book": [65],
        "amharic grade 2 science reference": [],
        "amharic grade 2 science teachers guide": [288],
        "amharic grade 2 science question": [],
        "amharic grade 2 art text book": [64],
        "amharic grade 2 art reference": [],
        "amharic grade 2 art teachers guide": [287],
        "amharic grade 2 art question": [],
        "amharic grade 2 health text book": [68],
        "amharic grade 2 health reference": [],
        "amharic grade 2 health teachers guide": [284],
        "amharic grade 2 health question": [],
        "amharic grade 2 moral text book": [467],
        "amharic grade 2 moral reference": [],
        "amharic grade 2 moral teachers guide": [],
        "amharic grade 2 moral question": [],
        "amharic grade 3 amharic text book": [83],
        "amharic grade 3 amharic reference": [],
        "amharic grade 3 amharic teachers guide": [298],
        "amharic grade 3 amharic question": [],
        "amharic grade 3 english text book": [85],
        "amharic grade 3 english reference": [],
        "amharic grade 3 english teachers guide": [300],
        "amharic grade 3 english question": [],
        "amharic grade 3 math text book": [479],
        "amharic grade 3 math reference": [],
        "amharic grade 3 math teachers guide": [301],
        "amharic grade 3 math question": [],
        "amharic grade 3 science text book": [82],
        # Add more as needed
        "amharic grade 3 science reference": [],
        "amharic grade 3 science teachers guide": [303],
        "amharic grade 3 science question": [],
        "amharic grade 3 art text book": [81],
        "amharic grade 3 art reference": [],
        "amharic grade 3 art teachers guide": [302],
        "amharic grade 3 art question": [],
        "amharic grade 3 health text book": [84],
        "amharic grade 3 health reference": [],
        "amharic grade 3 health teachers guide": [299],
        "amharic grade 3 health question": [],
        "amharic grade 3 moral text book": [468],
        "amharic grade 3 moral reference": [],
        "amharic grade 3 moral teachers guide": [],
        "amharic grade 3 moral question": [],
        "amharic grade 4 amharic text book": [98],
        "amharic grade 4 amharic reference": [],
        "amharic grade 4 amharic teachers guide": [311],
        "amharic grade 4 amharic question": [],
        "amharic grade 4 english text book": [100],
        "amharic grade 4 english reference": [],
        "amharic grade 4 english teachers guide": [313],
        "amharic grade 4 english question": [],
        "amharic grade 4 math text book": [101],
        "amharic grade 4 math reference": [],
        "amharic grade 4 math teachers guide": [314],
        "amharic grade 4 math question": [],
        "amharic grade 4 science text book": [475],
        "amharic grade 4 science reference": [],
        "amharic grade 4 science teachers guide": [316],
        "amharic grade 4 science question": [],
        "amharic grade 4 art text book": [474],
        "amharic grade 4 art reference": [],
        "amharic grade 4 art teachers guide": [315],
        "amharic grade 4 art question": [],
        "amharic grade 4 health text book": [99],
        "amharic grade 4 health reference": [],
        "amharic grade 4 health teachers guide": [312],
        "amharic grade 4 health question": [],
        "amharic grade 4 moral text book": [469],
        "amharic grade 4 moral reference": [],
        "amharic grade 4 moral teachers guide": [],
        "amharic grade 4 moral question": [],
        "amharic grade 5 amharic text book": [117],
        "amharic grade 5 amharic reference": [],
        "amharic grade 5 amharic teachers guide": [327],
        "amharic grade 5 amharic question": [],
        "amharic grade 5 english text book": [119],
        "amharic grade 5 english reference": [],
        "amharic grade 5 english teachers guide": [],
        "amharic grade 5 english question": [],
        "amharic grade 5 afaan oromoo text book": [118],
        "amharic grade 5 afaan oromoo reference": [],
        "amharic grade 5 afaan oromoo teachers guide": [331],
        "amharic grade 5 afaan oromoo question": [],
        "amharic grade 5 math text book": [120],
        "amharic grade 5 math reference": [],
        "amharic grade 5 math teachers guide": [329],
        "amharic grade 5 math question": [],
        "amharic grade 5 science text book": [116],
        "amharic grade 5 science reference": [],
        "amharic grade 5 science teachers guide": [326],
        "amharic grade 5 science question": [],
        "amharic grade 5 art text book": [115],
        "amharic grade 5 art reference": [],
        "amharic grade 5 art teachers guide": [332],
        "amharic grade 5 art question": [],

        # Grade 5 Health
        "amharic grade 5 health text book": [121],
        "amharic grade 5 health reference": [],
        "amharic grade 5 health teachers guide": [328],
        "amharic grade 5 health question": [],

        # Grade 5 Moral
        "amharic grade 5 moral text book": [470],
        "amharic grade 5 moral reference": [],
        "amharic grade 5 moral teachers guide": [],
        "amharic grade 5 moral question": [],

        # Grade 6 Amharic
        "amharic grade 6 amharic text book": [137],
        "amharic grade 6 amharic reference": [],
        "amharic grade 6 amharic teachers guide": [342],
        "amharic grade 6 amharic question": [],

        # Grade 6 English
        "amharic grade 6 english text book": [138],
        "amharic grade 6 english reference": [],
        "amharic grade 6 english teachers guide": [341],
        "amharic grade 6 english question": [],

        # Grade 6 Afaan Oromoo
        "amharic grade 6 afaan oromoo text book": [136],
        "amharic grade 6 afaan oromoo reference": [],
        "amharic grade 6 afaan oromoo teachers guide": [346],
        "amharic grade 6 afaan oromoo question": [],

        # Grade 6 Math
        "amharic grade 6 math text book": [140],
        "amharic grade 6 math reference": [],
        "amharic grade 6 math teachers guide": [344],
        "amharic grade 6 math question": [],

        # Grade 6 Science
        "amharic grade 6 science text book": [135],
        "amharic grade 6 science reference": [],
        "amharic grade 6 science teachers guide": [347],
        "amharic grade 6 science question": [],

        # Grade 6 Art
        "amharic grade 6 art text book": [134],
        "amharic grade 6 art reference": [],
        "amharic grade 6 art teachers guide": [345],
        "amharic grade 6 art question": [],

        # Grade 6 Health
        "amharic grade 6 health text book": [139],
        "amharic grade 6 health reference": [],
        "amharic grade 6 health teachers guide": [343],
        "amharic grade 6 health question": [],

        # Grade 6 Moral
        "amharic grade 6 moral text book": [471],
        "amharic grade 6 moral reference": [],
        "amharic grade 6 moral teachers guide": [],
        "amharic grade 6 moral question": [],

        'amharic grade 7 amharic text book': [154],
        'amharic grade 7 amharic reference': [],
        'amharic grade 7 amharic teachers guide': [358],
        'amharic grade 7 amharic question': [],
        
        'amharic grade 7 english text book': [159],
        'amharic grade 7 english reference': [],
        'amharic grade 7 english teachers guide': [359],
        'amharic grade 7 english question': [],
        
        'amharic grade 7 afaan oromoo text book': [155],
        'amharic grade 7 afaan oromoo reference': [],
        'amharic grade 7 afaan oromoo teachers guide': [360],
        'amharic grade 7 afaan oromoo question': [],
        
        'amharic grade 7 math text book': [160],
        'amharic grade 7 math reference': [],
        'amharic grade 7 math teachers guide': [363],
        'amharic grade 7 math question': [],
        
        'amharic grade 7 science text book': [162],
        'amharic grade 7 science reference': [],
        'amharic grade 7 science teachers guide': [365],
        'amharic grade 7 science question': [],
        
        'amharic grade 7 social studies text book': [161],
        'amharic grade 7 social studies reference': [],
        'amharic grade 7 social studies teachers guide': [364],
        'amharic grade 7 social studies question': [],
        
        'amharic grade 7 civics text book': [157],
        'amharic grade 7 civics reference': [],
        'amharic grade 7 civics teachers guide': [368],
        'amharic grade 7 civics question': [],
        
        'amharic grade 7 art text book': [153],
        'amharic grade 7 art reference': [],
        'amharic grade 7 art teachers guide': [366],
        'amharic grade 7 art question': [],
        
        'amharic grade 7 IT text book': [158],
        'amharic grade 7 IT reference': [],
        'amharic grade 7 IT teachers guide': [],
        'amharic grade 7 IT question': [],
        
        'amharic grade 7 vocation text book': [477],
        'amharic grade 7 vocation reference': [],
        'amharic grade 7 vocation teachers guide': [],
        'amharic grade 7 vocation question': [],
        
        'amharic grade 7 health text book': [156],
        'amharic grade 7 health reference': [],
        'amharic grade 7 health teachers guide': [367],
        'amharic grade 7 health question': [],
        
        'amharic grade 7 moral text book': [],
        'amharic grade 7 moral reference': [],
        'amharic grade 7 moral teachers guide': [],
        'amharic grade 7 moral question': [],

        "amharic grade 8 amharic text book": [177],
        "amharic grade 8 amharic reference": [],
        "amharic grade 8 amharic teachers guide": [382],
        "amharic grade 8 amharic question": [],
        "amharic grade 8 english text book": [180],
        "amharic grade 8 english reference": [],
        "amharic grade 8 english teachers guide": [],
        "amharic grade 8 english question": [],
        "amharic grade 8 afaan oromoo text book": [178],
        "amharic grade 8 afaan oromoo reference": [],
        "amharic grade 8 afaan oromoo teachers guide": [],
        "amharic grade 8 afaan oromoo question": [],
        "amharic grade 8 math text book": [182],
        "amharic grade 8 math reference": [],
        "amharic grade 8 math teachers guide": [386],
        "amharic grade 8 math question": [],
        "amharic grade 8 science text book": [184],
        "amharic grade 8 science reference": [],
        "amharic grade 8 science teachers guide": [389],
        "amharic grade 8 science question": [],
        "amharic grade 8 social studies text book": [185],
        "amharic grade 8 social studies reference": [],
        "amharic grade 8 social studies teachers guide": [390],
        "amharic grade 8 social studies question": [],
        "amharic grade 8 civics text book": [179],
        "amharic grade 8 civics reference": [],
        "amharic grade 8 civics teachers guide": [391],
        "amharic grade 8 civics question": [],
        "amharic grade 8 art text book": [183],
        "amharic grade 8 art reference": [],
        "amharic grade 8 art teachers guide": [388],
        "amharic grade 8 art question": [],
        "amharic grade 8 IT text book": [181],
        "amharic grade 8 IT reference": [],
        "amharic grade 8 IT teachers guide": [],
        "amharic grade 8 IT question": [],
        "amharic grade 8 vocation text book": [478],
        "amharic grade 8 vocation reference": [],
        "amharic grade 8 vocation teachers guide": [],
        "amharic grade 8 vocation question": [],
        "amharic grade 8 health text book": [186],
        "amharic grade 8 health reference": [],
        "amharic grade 8 health teachers guide": [381],
        "amharic grade 8 health question": [],
        "amharic grade 8 moral text book": [],
        "amharic grade 8 moral reference": [],
        "amharic grade 8 moral teachers guide": [],
        "amharic grade 8 moral question": [],

        'oromic grade 1 afaan oromoo text book': [57],
        'oromic grade 1 afaan oromoo reference': [],
        'oromic grade 1 afaan oromoo teachers guide': [],
        'oromic grade 1 afaan oromoo question': [],
        'oromic grade 1 english text book': [53],
        'oromic grade 1 english reference': [],
        'oromic grade 1 english teachers guide': [278],
        'oromic grade 1 english question': [],
        'oromic grade 1 math text book': [56],
        'oromic grade 1 math reference': [],
        'oromic grade 1 math teachers guide': [281],
        'oromic grade 1 math question': [],
        'oromic grade 1 science text book': [59],
        'oromic grade 1 science reference': [],
        'oromic grade 1 science teachers guide': [279],
        'oromic grade 1 science question': [],
        'oromic grade 1 art text book': [58],
        'oromic grade 1 art reference': [],
        'oromic grade 1 art teachers guide': [282],
        'oromic grade 1 art question': [],
        'oromic grade 1 health text book': [54],
        'oromic grade 1 health reference': [],
        'oromic grade 1 health teachers guide': [280],
        'oromic grade 1 health question': [],
        'oromic grade 1 moral text book': [60],
        'oromic grade 1 moral reference': [],
        'oromic grade 1 moral teachers guide': [],
        'oromic grade 1 moral question': [],
        'oromic grade 1 geda text book': [55],
        'oromic grade 1 geda reference': [],
        'oromic grade 1 geda teachers guide': [],
        'oromic grade 1 geda question': [],
        'oromic grade 2 afaan oromoo text book': [71],
        'oromic grade 2 afaan oromoo reference': [],
        'oromic grade 2 afaan oromoo teachers guide': [290],
        'oromic grade 2 afaan oromoo question': [],
        'oromic grade 2 english text book': [72],
        'oromic grade 2 english reference': [],
        'oromic grade 2 english teachers guide': [291],
        'oromic grade 2 english question': [],
        'oromic grade 2 math text book': [74],
        'oromic grade 2 math reference': [],
        'oromic grade 2 math teachers guide': [294],
        'oromic grade 2 math question': [],
        'oromic grade 2 science text book': [78],
        'oromic grade 2 science reference': [],
        'oromic grade 2 science teachers guide': [296],
        'oromic grade 2 science question': [],
        'oromic grade 2 art text book': [76],
        'oromic grade 2 art reference': [],
        'oromic grade 2 art teachers guide': [295],
        'oromic grade 2 art question': [],
        'oromic grade 2 health text book': [75],
        'oromic grade 2 health reference': [],
        'oromic grade 2 health teachers guide': [292],
        'oromic grade 2 health question': [],
        'oromic grade 2 moral text book': [77],
        'oromic grade 2 moral reference': [],
        'oromic grade 2 moral teachers guide': [],
        'oromic grade 2 moral question': [],
        'oromic grade 2 geda text book': [73],
        'oromic grade 2 geda reference': [],
        'oromic grade 2 geda teachers guide': [293],
        'oromic grade 2 geda question': [],

        "oromic grade 3 afaan oromoo text book": [92],
        "oromic grade 3 afaan oromoo reference": [],
        "oromic grade 3 afaan oromoo teachers guide": [],
        "oromic grade 3 afaan oromoo question": [],
        "oromic grade 3 english text book": [88],
        "oromic grade 3 english reference": [],
        "oromic grade 3 english teachers guide": [305],
        "oromic grade 3 english question": [],
        "oromic grade 3 math text book": [91],
        "oromic grade 3 math reference": [],
        "oromic grade 3 math teachers guide": [308],
        "oromic grade 3 math question": [],
        "oromic grade 3 science text book": [94],
        "oromic grade 3 science reference": [],
        "oromic grade 3 science teachers guide": [306],
        "oromic grade 3 science question": [],
        "oromic grade 3 art text book": [93],
        "oromic grade 3 art reference": [],
        "oromic grade 3 art teachers guide": [309],
        "oromic grade 3 art question": [],
        "oromic grade 3 health text book": [89],
        "oromic grade 3 health reference": [],
        "oromic grade 3 health teachers guide": [307],
        "oromic grade 3 health question": [],
        "oromic grade 3 moral text book": [95],
        "oromic grade 3 moral reference": [],
        "oromic grade 3 moral teachers guide": [],
        "oromic grade 3 moral question": [],
        "oromic grade 3 geda text book": [90],
        "oromic grade 3 geda reference": [],
        "oromic grade 3 geda teachers guide": [],
        "oromic grade 3 geda question": [],
        
        # Grade 4
        "oromic grade 4 afaan oromoo text book": [110],
        "oromic grade 4 afaan oromoo reference": [],
        "oromic grade 4 afaan oromoo teachers guide": [318],
        "oromic grade 4 afaan oromoo question": [],
        "oromic grade 4 english text book": [111],
        "oromic grade 4 english reference": [],
        "oromic grade 4 english teachers guide": [319],
        "oromic grade 4 english question": [],
        "oromic grade 4 math text book": [106],
        "oromic grade 4 math reference": [],
        "oromic grade 4 math teachers guide": [322],
        "oromic grade 4 math question": [],
        "oromic grade 4 science text book": [109],
        "oromic grade 4 science reference": [],
        "oromic grade 4 science teachers guide": [324],
        "oromic grade 4 science question": [],
        "oromic grade 4 art text book": [107],
        "oromic grade 4 art reference": [],
        "oromic grade 4 art teachers guide": [323],
        "oromic grade 4 art question": [],
        "oromic grade 4 health text book": [105],
        "oromic grade 4 health reference": [],
        "oromic grade 4 health teachers guide": [320],
        "oromic grade 4 health question": [],
        "oromic grade 4 moral text book": [108],
        "oromic grade 4 moral reference": [],
        "oromic grade 4 moral teachers guide": [],
        "oromic grade 4 moral question": [],
        "oromic grade 4 geda text book": [112],
        "oromic grade 4 geda reference": [],
        "oromic grade 4 geda teachers guide": [321],
        "oromic grade 4 geda question": [],

        'oromic grade 5 amharic text book': [128],
        'oromic grade 5 amharic reference': [],
        'oromic grade 5 amharic teachers guide': [339],
        'oromic grade 5 amharic question': [],
        'oromic grade 5 english text book': [124],
        'oromic grade 5 english reference': [],
        'oromic grade 5 english teachers guide': [334],
        'oromic grade 5 english question': [],
        'oromic grade 5 afaan oromoo text book': [123],
        'oromic grade 5 afaan oromoo reference': [],
        'oromic grade 5 afaan oromoo teachers guide': [],
        'oromic grade 5 afaan oromoo question': [],
        'oromic grade 5 math text book': [127],
        'oromic grade 5 math reference': [],
        'oromic grade 5 math teachers guide': [338],
        'oromic grade 5 math question': [],
        'oromic grade 5 science text book': [130],
        'oromic grade 5 science reference': [],
        'oromic grade 5 science teachers guide': [335],
        'oromic grade 5 science question': [],
        'oromic grade 5 art text book': [129],
        'oromic grade 5 art reference': [],
        'oromic grade 5 art teachers guide': [337],
        'oromic grade 5 art question': [],
        'oromic grade 5 health text book': [125],
        'oromic grade 5 health reference': [336],
        'oromic grade 5 health teachers guide': [],
        'oromic grade 5 health question': [],
        'oromic grade 5 moral text book': [131],
        'oromic grade 5 moral reference': [],
        'oromic grade 5 moral teachers guide': [],
        'oromic grade 5 moral question': [],
        'oromic grade 5 geda text book': [126],
        'oromic grade 5 geda reference': [],
        'oromic grade 5 geda teachers guide': [],
        'oromic grade 5 geda question': [],
        'oromic grade 6 amharic text book': [150],
        'oromic grade 6 amharic reference': [],
        'oromic grade 6 amharic teachers guide': [356],
        'oromic grade 6 amharic question': [],
        'oromic grade 6 english text book': [143],
        'oromic grade 6 english reference': [],
        'oromic grade 6 english teachers guide': [349],
        'oromic grade 6 english question': [],
        'oromic grade 6 afaan oromoo text book': [142],
        'oromic grade 6 afaan oromoo reference': [],
        'oromic grade 6 afaan oromoo teachers guide': [350],
        'oromic grade 6 afaan oromoo question': [],
        'oromic grade 6 math text book': [146],
        'oromic grade 6 math reference': [],
        'oromic grade 6 math teachers guide': [353],
        'oromic grade 6 math question': [],
        'oromic grade 6 science text book': [149],
        'oromic grade 6 science reference': [],
        'oromic grade 6 science teachers guide': [355],
        'oromic grade 6 science question': [],
        'oromic grade 6 art text book': [147],
        'oromic grade 6 art reference': [],
        'oromic grade 6 art teachers guide': [354],
        'oromic grade 6 art question': [],
        'oromic grade 6 health text book': [145],
        'oromic grade 6 health reference': [],
        'oromic grade 6 health teachers guide': [351],
        'oromic grade 6 health question': [],
        'oromic grade 6 moral text book': [148],
        'oromic grade 6 geda text book': [144],
        'oromic grade 6 geda teachers guide': [352],
        'oromic grade 7 amharic text book': [165],
        'oromic grade 7 amharic teachers guide': [379],
        'oromic grade 7 english text book': [167],
        'oromic grade 7 english teachers guide': [371],
        'oromic grade 7 afaan oromoo text book': [164],
        'oromic grade 7 math text book': [170],
        'oromic grade 7 math teachers guide': [375],
        'oromic grade 7 science text book': [174],
        'oromic grade 7 science teachers guide': [372],
        'oromic grade 7 social studies text book': [166],
        'oromic grade 7 civics text book': [172],
        'oromic grade 7 civics teachers guide': [370],
        'oromic grade 7 art text book': [173],
        'oromic grade 7 art teachers guide': [373],
        'oromic grade 7 IT text book': [171],
        'oromic grade 7 IT teachers guide': [374],
        'oromic grade 7 health text book': [168],
        'oromic grade 7 health teachers guide': [376],
        'oromic grade 7 geda text book': [169],
        "oromic grade 7 geda reference": [],
        "oromic grade 7 geda teachers guide": [],
        "oromic grade 7 geda question": [],
        "oromic grade 8 amharic text book": [],
        "oromic grade 8 amharic reference": [],
        "oromic grade 8 amharic teachers guide": [403],
        "oromic grade 8 amharic question": [],
        "oromic grade 8 english text book": [190],
        "oromic grade 8 english reference": [],
        "oromic grade 8 english teachers guide": [395],
        "oromic grade 8 english question": [],
        "oromic grade 8 afaan oromoo text book": [188],
        "oromic grade 8 afaan oromoo reference": [],
        "oromic grade 8 afaan oromoo teachers guide": [],
        "oromic grade 8 afaan oromoo question": [],
        "oromic grade 8 math text book": [193],
        "oromic grade 8 math reference": [],
        "oromic grade 8 math teachers guide": [393],
        "oromic grade 8 math question": [],
        "oromic grade 8 science text book": [197],
        "oromic grade 8 science reference": [],
        "oromic grade 8 science teachers guide": [398],
        "oromic grade 8 science question": [],
        "oromic grade 8 social studies text book": [189],
        "oromic grade 8 social studies reference": [],
        "oromic grade 8 social studies teachers guide": [401],
        "oromic grade 8 social studies question": [],
        "oromic grade 8 civics text book": [195],
        "oromic grade 8 civics reference": [],
        "oromic grade 8 civics teachers guide": [394],
        "oromic grade 8 civics question": [],
        "oromic grade 8 art text book": [196],
        "oromic grade 8 art reference": [],
        "oromic grade 8 art teachers guide": [400],
        "oromic grade 8 art question": [],
        "oromic grade 8 IT text book": [194],
        "oromic grade 8 IT reference": [],
        "oromic grade 8 IT teachers guide": [399],
        "oromic grade 8 IT question": [],
        "oromic grade 8 vocation text book": [],
        "oromic grade 8 vocation reference": [],
        "oromic grade 8 vocation teachers guide": [],
        "oromic grade 8 vocation question": [],
        "oromic grade 8 health text book": [191],
        "oromic grade 8 health reference": [],
        "oromic grade 8 health teachers guide": [396],
        "oromic grade 8 health question": [],
        "oromic grade 8 moral text book": [],
        "oromic grade 8 moral reference": [],
        "oromic grade 8 moral teachers guide": [],
        "oromic grade 8 moral question": [],
        "oromic grade 8 geda text book": [192],
        "oromic grade 8 geda reference": [],
        "oromic grade 8 geda teachers guide": [],
        "oromic grade 8 geda question": [],
        "grade 9 amharic text book": [204],
        "grade 9 amharic reference": [],
        "grade 9 amharic teachers guide": [406],
        "grade 9 amharic question": [],
        "grade 9 english text book": [203],
        "grade 9 english reference": [],
        "grade 9 english teachers guide": [410],
        "grade 9 english question": [],
        "grade 9 math text book": [207],
        "grade 9 math reference": [],
        "grade 9 math teachers guide": [412],
        "grade 9 math question": [],
        "grade 9 biology text book": [200],
        "grade 9 biology reference": [],
        "grade 9 biology teachers guide": [407],
        "grade 9 biology question": [],
        "grade 9 citizenship text book": [201],
        "grade 9 citizenship reference": [],
        "grade 9 citizenship teachers guide": [409],
        "grade 9 citizenship question": [],
        "grade 9 oromic text book": [199],
        "grade 9 oromic reference": [],
        "grade 9 oromic teachers guide": [],
        "grade 9 oromic question": [],
        "grade 9 physics text book": [211],
        "grade 9 physics reference": [],
        "grade 9 physics teachers guide": [416],
        "grade 9 physics question": [],
        "grade 9 chemistry text book": [205],
        "grade 9 chemistry reference": [],
        "grade 9 chemistry teachers guide": [408],
        "grade 9 chemistry question": [],
        "grade 9 geography text book": [206],
        "grade 9 geography reference": [],
        "grade 9 geography teachers guide": [411],
        "grade 9 geography question": [],
        "grade 9 history text book": [208],
        "grade 9 history reference": [],
        "grade 9 history teachers guide": [413],
        "grade 9 history question": [],
        "grade 9 ict text book": [210],
        "grade 9 ict reference": [],
        "grade 9 ict teachers guide": [415],
        "grade 9 ict question": [],
        "grade 9 economics text book": [202],
        "grade 9 economics reference": [],
        "grade 9 economics teachers guide": [],
        "grade 9 economics question": [],
        "grade 9 hpe text book": [209],
        "grade 9 hpe reference": [],
        "grade 9 hpe teachers guide": [414],
        "grade 9 hpe question": [],
        "grade 9 art text book": [212],
        "grade 9 art reference": [],
        "grade 9 art teachers guide": [417],
        "grade 9 art question": [],
        "grade 10 amharic text book": [215],
        "grade 10 amharic reference": [],
        "grade 10 amharic teachers guide": [419],
        "grade 10 amharic question": [],
        
        "grade 10 english text book": [220],
        "grade 10 english reference": [],
        "grade 10 english teachers guide": [424],
        "grade 10 english question": [],
        
        "grade 10 math text book": [225],
        "grade 10 math reference": [],
        "grade 10 math teachers guide": [430],
        "grade 10 math question": [],
        
        "grade 10 biology text book": [216],
        "grade 10 biology reference": [],
        "grade 10 biology teachers guide": [420],
        "grade 10 biology question": [],
        
        "grade 10 citizenship text book": [218],
        "grade 10 citizenship reference": [],
        "grade 10 citizenship teachers guide": [422],
        "grade 10 citizenship question": [],
        
        "grade 10 oromic text book": [214],
        "grade 10 oromic reference": [],
        "grade 10 oromic teachers guide": [],
        "grade 10 oromic question": [],
        
        "grade 10 physics text book": [226],
        "grade 10 physics reference": [],
        "grade 10 physics teachers guide": [],
        "grade 10 physics question": [],
        
        "grade 10 chemistry text book": [217],
        "grade 10 chemistry reference": [],
        "grade 10 chemistry teachers guide": [421],
        "grade 10 chemistry question": [],
        
        "grade 10 geography text book": [221],
        "grade 10 geography reference": [],
        "grade 10 geography teachers guide": [425],
        "grade 10 geography question": [],
        
        "grade 10 history text book": [222],
        "grade 10 history reference": [],
        "grade 10 history teachers guide": [427],
        "grade 10 history question": [],
        
        "grade 10 ict text book": [224],
        "grade 10 ict reference": [],
        "grade 10 ict teachers guide": [429],
        "grade 10 ict question": [],
        
        "grade 10 economics text book": [219],
        "grade 10 economics reference": [],
        "grade 10 economics teachers guide": [423],
        "grade 10 economics question": [],
        
        "grade 10 hpe text book": [223],
        "grade 10 hpe reference": [],
        "grade 10 hpe teachers guide": [428],
        "grade 10 hpe question": [],
        
        "grade 10 art text book": [],
        "grade 10 art reference": [],
        "grade 10 art teachers guide": [],
        "grade 10 art question": [],

        # Grade 11 Subjects
        "grade 11 english text book": [232],
        "grade 11 english reference": [],
        "grade 11 english teachers guide": [434],
        "grade 11 english question": [],
        
        "grade 11 math text book": [234],
        "grade 11 math reference": [],
        "grade 11 math teachers guide": [436],
        "grade 11 math question": [],
        
        "grade 11 biology text book": [230],
        "grade 11 biology reference": [],
        "grade 11 biology teachers guide": [],
        "grade 11 biology question": [],
        
        "grade 11 agriculture text book": [229],
        "grade 11 agriculture reference": [],
        "grade 11 agriculture teachers guide": [432],
        "grade 11 agriculture question": [],
        
        "grade 11 physics text book": [235],
        "grade 11 physics reference": [],
        "grade 11 physics teachers guide": [437],
        "grade 11 physics question": [],
        
        "grade 11 chemistry text book": [231],
        "grade 11 chemistry reference": [],
        "grade 11 chemistry teachers guide": [433],
        "grade 11 chemistry question": [],
        
        "grade 11 ict text book": [233],
        "grade 11 ict reference": [],
        "grade 11 ict teachers guide": [435],
        "grade 11 ict question": [],

        # Grade 12 Subjects
        "grade 12 english text book": [256],
        "grade 12 english reference": [],
        "grade 12 english teachers guide": [449],
        "grade 12 english question": [],
        
        "grade 12 math text book": [258],
        "grade 12 math reference": [],
        "grade 12 math teachers guide": [451],
        "grade 12 math question": [],
        
        "grade 12 biology text book": [254],
        "grade 12 biology reference": [],
        "grade 12 biology teachers guide": [447],
        "grade 12 biology question": [],
        
        "grade 12 agriculture text book": [253],
        "grade 12 agriculture reference": [],
        "grade 12 agriculture teachers guide": [446],
        "grade 12 agriculture question": [],
        
        "grade 12 physics text book": [259],
        "grade 12 physics reference": [],
        "grade 12 physics teachers guide": [452],
        "grade 12 physics question": [],
        
        "grade 12 chemistry text book": [255],
        "grade 12 chemistry reference": [],
        "grade 12 chemistry teachers guide": [448],
        "grade 12 chemistry question": [],
        
        "grade 12 ict text book": [257],
        "grade 12 ict reference": [],
        "grade 12 ict teachers guide": [450],
        "grade 12 ict question": [],

        # Grade 11 Subjects
        "grade 11 english text book": [238],
        "grade 11 english reference": [],
        "grade 11 english teachers guide": [440],
        "grade 11 english question": [],
        
        "grade 11 math text book": [242],
        "grade 11 math reference": [],
        "grade 11 math teachers guide": [444],
        "grade 11 math question": [],
        
        "grade 11 geography text book": [239],
        "grade 11 geography reference": [],
        "grade 11 geography teachers guide": [441],
        "grade 11 geography question": [],
        
        "grade 11 history text book": [240],
        "grade 11 history reference": [],
        "grade 11 history teachers guide": [442],
        "grade 11 history question": [],
        
        "grade 11 economics text book": [237],
        "grade 11 economics reference": [],
        "grade 11 economics teachers guide": [439],
        "grade 11 economics question": [],
        
        "grade 11 ict text book": [241],
        "grade 11 ict reference": [],
        "grade 11 ict teachers guide": [443],
        "grade 11 ict question": [],

        # Grade 12 Subjects
        "grade 12 english text book": [262],
        "grade 12 english reference": [],
        "grade 12 english teachers guide": [419],
        "grade 12 english question": [],
        
        "grade 12 math text book": [266],
        "grade 12 math reference": [],
        "grade 12 math teachers guide": [424],
        "grade 12 math question": [],
        
        "grade 12 geography text book": [263],
        "grade 12 geography reference": [],
        "grade 12 geography teachers guide": [430],
        "grade 12 geographyquestion": [],  # Note: Typo in original (missing space)
        
        "grade 12 history text book": [264],
        "grade 12 history reference": [],
        "grade 12 history teachers guide": [420],
        "grade 12 history question": [],
        
        "grade 12 economics text book": [261],
        "grade 12 economics reference": [],
        "grade 12 economics teachers guide": [422],
        "grade 12 economics question": [],
        
        "grade 12 ict text book": [265],
        "grade 12 ict reference": [],
        "grade 12 ict teachers guide": [],
        "grade 12 ict question": []

        



    }
    
    async def get_id(self, button_clicked):
        id = self._query_data.get(button_clicked, [])
        return id