# core/domain/states.py


class BotState():
    # Main states
    START = "original state"
    AWAITING_AVAILABILITY = "availability"
    AWAITING_NECESSARY = "necessary"
    AWAITING_COURSE_SCHEDULE = "course schedule"
    AWAITING_STUDENT = "student"
    AWAITING_STUDENT_INFO = "student info"
    AWAITING_STUDENT_SCHEDULE = "student schedule"
    AWAITING_GRADE = "grade"

    # KG states
    AWAITING_KG_LANGUAGE = "kg language"
    AWAITING_KG_AMHARIC = "kg amharic"
    AWAITING_KG_OROMIC = "kg oromic"

    # Grade language selection states
    AWAITING_GRADE_1_LANGUAGE = "Grade 1️⃣ language"
    AWAITING_GRADE_2_LANGUAGE = "Grade 2️⃣ language"
    AWAITING_GRADE_3_LANGUAGE = "Grade 3️⃣ language"
    AWAITING_GRADE_4_LANGUAGE = "Grade 4️⃣ language"
    AWAITING_GRADE_5_LANGUAGE = "Grade 5️⃣ language"
    AWAITING_GRADE_6_LANGUAGE = "Grade 6️⃣ language"
    AWAITING_GRADE_7_LANGUAGE = "Grade 7️⃣ language"
    AWAITING_GRADE_8_LANGUAGE = "Grade 8️⃣ language"

    # Amharic format states
    AWAITING_AMHARIC_GRADE_1_FORMAT = "amharic grade 1 format"
    AWAITING_AMHARIC_GRADE_2_FORMAT = "amharic grade 2 format"
    AWAITING_AMHARIC_GRADE_3_FORMAT = "amharic grade 3 format"
    AWAITING_AMHARIC_GRADE_4_FORMAT = "amharic grade 4 format"
    AWAITING_AMHARIC_GRADE_5_FORMAT = "amharic grade 5 format"
    AWAITING_AMHARIC_GRADE_6_FORMAT = "amharic grade 6 format"
    AWAITING_AMHARIC_GRADE_7_FORMAT = "amharic grade 7 format"
    AWAITING_AMHARIC_GRADE_8_FORMAT = "amharic grade 8 format"

    # Oromic format states
    AWAITING_OROMIC_GRADE_1_FORMAT = "oromic grade 1 format"
    AWAITING_OROMIC_GRADE_2_FORMAT = "oromic grade 2 format"
    AWAITING_OROMIC_GRADE_3_FORMAT = "oromic grade 3 format"
    AWAITING_OROMIC_GRADE_4_FORMAT = "oromic grade 4 format"
    AWAITING_OROMIC_GRADE_5_FORMAT = "oromic grade 5 format"
    AWAITING_OROMIC_GRADE_6_FORMAT = "oromic grade 6 format"
    AWAITING_OROMIC_GRADE_7_FORMAT = "oromic grade 7 format"
    AWAITING_OROMIC_GRADE_8_FORMAT = "oromic grade 8 format"

    # Grade 9-12 states
    AWAITING_GRADE_9_FORMAT = "Grade 9️⃣ format"
    AWAITING_GRADE_9_COURSES = "Grade 9️⃣ courses"
    AWAITING_GRADE_10_FORMAT = "Grade 1️⃣0️⃣ format"
    AWAITING_GRADE_10_COURSES = "Grade 1️⃣0️⃣ courses"
    AWAITING_GRADE_11_CATEGORY = "Grade 1️⃣1️⃣ catagory"
    AWAITING_GRADE_12_CATEGORY = "Grade 1️⃣2️⃣ catagory"

    # Natural/Social science states
    AWAITING_NATURAL_GRADE_11_FORMAT = "natural grade 11 format"
    AWAITING_NATURAL_GRADE_11 = "natural grade 11"
    AWAITING_NATURAL_GRADE_12_FORMAT = "natural grade 12 format"
    AWAITING_NATURAL_GRADE_12 = "natural grade 12"
    AWAITING_SOCIAL_GRADE_11_FORMAT = "social grade 11 format"
    AWAITING_SOCIAL_GRADE_11 = "social grade 11"
    AWAITING_SOCIAL_GRADE_12_FORMAT = "social grade 12 format"
    AWAITING_SOCIAL_GRADE_12 = "social grade 12"

    # Subject states for grades 9-10
    AWAITING_GRADE_9_AMHARIC = "grade 9 amharic"
    AWAITING_GRADE_9_ENGLISH = "grade 9 english"
    AWAITING_GRADE_9_MATH = "grade 9 math"
    AWAITING_GRADE_9_BIOLOGY = "grade 9 biology"
    AWAITING_GRADE_9_CITIZENSHIP = "grade 9 citizenship"
    AWAITING_GRADE_9_OROMIC = "grade 9 oromic"
    AWAITING_GRADE_9_PHYSICS = "grade 9 physics"
    AWAITING_GRADE_9_CHEMISTRY = "grade 9 chemistry"
    AWAITING_GRADE_9_GEOGRAPHY = "grade 9 geography"
    AWAITING_GRADE_9_HISTORY = "grade 9 history"
    AWAITING_GRADE_9_ICT = "grade 9 ict"
    AWAITING_GRADE_9_ECONOMICS = "grade 9 economics"
    AWAITING_GRADE_9_HPE = "grade 9 hpe"
    AWAITING_GRADE_9_ART = "grade 9 art"

    AWAITING_GRADE_10_AMHARIC = "grade 10 amharic"
    AWAITING_GRADE_10_ENGLISH = "grade 10 english"
    AWAITING_GRADE_10_MATH = "grade 10 math"
    AWAITING_GRADE_10_BIOLOGY = "grade 10 biology"
    AWAITING_GRADE_10_CITIZENSHIP = "grade 10 citizenship"
    AWAITING_GRADE_10_OROMIC = "grade 10 oromic"
    AWAITING_GRADE_10_PHYSICS = "grade 10 physics"
    AWAITING_GRADE_10_CHEMISTRY = "grade 10 chemistry"
    AWAITING_GRADE_10_GEOGRAPHY = "grade 10 geography"
    AWAITING_GRADE_10_HISTORY = "grade 10 history"
    AWAITING_GRADE_10_ICT = "grade 10 ict"
    AWAITING_GRADE_10_ECONOMICS = "grade 10 economics"
    AWAITING_GRADE_10_HPE = "grade 10 hpe"
    AWAITING_GRADE_10_ART = "grade 10 art"

    # Natural/Social science subject states
    AWAITING_NATURAL_GRADE_11_ENGLISH = "grade 11 english"
    AWAITING_NATURAL_GRADE_11_MATH = "grade 11 math"
    AWAITING_NATURAL_GRADE_11_BIOLOGY = "grade 11 biology"
    AWAITING_NATURAL_GRADE_11_PHYSICS = "grade 11 physics"
    AWAITING_NATURAL_GRADE_11_CHEMISTRY = "grade 11 chemistry"
    AWAITING_NATURAL_GRADE_11_ICT = "grade 11 ict"
    AWAITING_NATURAL_GRADE_11_AGRICULTURE = "grade 11 agriculture"

    AWAITING_SOCIAL_GRADE_11_ENGLISH = "grade 11 english"
    AWAITING_SOCIAL_GRADE_11_MATH = "grade 11 math"
    AWAITING_SOCIAL_GRADE_11_GEOGRAPHY = "grade 11 geography"
    AWAITING_SOCIAL_GRADE_11_HISTORY = "grade 11 history"
    AWAITING_SOCIAL_GRADE_11_ECONOMICS = "grade 11 economics"
    AWAITING_SOCIAL_GRADE_11_ICT = "grade 11 ict"

    AWAITING_NATURAL_GRADE_12_ENGLISH = "grade 12 english"
    AWAITING_NATURAL_GRADE_12_MATH = "grade 12 math"
    AWAITING_NATURAL_GRADE_12_BIOLOGY = "grade 12 biology"
    AWAITING_NATURAL_GRADE_12_PHYSICS = "grade 12 physics"
    AWAITING_NATURAL_GRADE_12_CHEMISTRY = "grade 12 chemistry"
    AWAITING_NATURAL_GRADE_12_ICT = "grade 12 ict"
    AWAITING_NATURAL_GRADE_12_AGRICULTURE = "grade 12 agriculture"

    AWAITING_SOCIAL_GRADE_12_ENGLISH = "grade 12 english"
    AWAITING_SOCIAL_GRADE_12_MATH = "grade 12 math"
    AWAITING_SOCIAL_GRADE_12_GEOGRAPHY = "grade 12 geography"
    AWAITING_SOCIAL_GRADE_12_HISTORY = "grade 12 history"
    AWAITING_SOCIAL_GRADE_12_ECONOMICS = "grade 12 economics"
    AWAITING_SOCIAL_GRADE_12_ICT = "grade 12 ict"


    # Amharic grade subject states (1-8)
    AWAITING_AMHARIC_GRADE_1= "amharic grade 1"
    AWAITING_AMHARIC_GRADE_2= "amharic grade 2"
    AWAITING_AMHARIC_GRADE_3= "amharic grade 3"
    AWAITING_AMHARIC_GRADE_4= "amharic grade 4"
    AWAITING_AMHARIC_GRADE_5= "amharic grade 5"
    AWAITING_AMHARIC_GRADE_6= "amharic grade 6"
    AWAITING_AMHARIC_GRADE_7= "amharic grade 7"
    AWAITING_AMHARIC_GRADE_8= "amharic grade 8"

    
    # Oromic grade subject states (1-8)
    AWAITING_OROMIC_GRADE_1= "oromic grade 1"
    AWAITING_OROMIC_GRADE_2= "oromic grade 2"
    AWAITING_OROMIC_GRADE_3= "oromic grade 3"
    AWAITING_OROMIC_GRADE_4= "oromic grade 4"
    AWAITING_OROMIC_GRADE_5= "oromic grade 5"
    AWAITING_OROMIC_GRADE_6= "oromic grade 6"
    AWAITING_OROMIC_GRADE_7= "oromic grade 7"
    AWAITING_OROMIC_GRADE_8= "oromic grade 8"

    # Amharic grade subject states (1-8)
    AWAITING_AMHARIC_GRADE_1_AMHARIC = "amharic grade 1 amharic"
    AWAITING_AMHARIC_GRADE_1_ENGLISH = "amharic grade 1 english"
    AWAITING_AMHARIC_GRADE_1_MATH = "amharic grade 1 math"
    AWAITING_AMHARIC_GRADE_1_SCIENCE = "amharic grade 1 science"
    AWAITING_AMHARIC_GRADE_1_ART = "amharic grade 1 art"
    AWAITING_AMHARIC_GRADE_1_HEALTH = "amharic grade 1 health"
    AWAITING_AMHARIC_GRADE_1_MORAL = "amharic grade 1 moral"

    AWAITING_AMHARIC_GRADE_2_AMHARIC = "amharic grade 2 amharic"
    AWAITING_AMHARIC_GRADE_2_ENGLISH = "amharic grade 2 english"
    AWAITING_AMHARIC_GRADE_2_MATH = "amharic grade 2 math"
    AWAITING_AMHARIC_GRADE_2_SCIENCE = "amharic grade 2 science"
    AWAITING_AMHARIC_GRADE_2_ART = "amharic grade 2 art"
    AWAITING_AMHARIC_GRADE_2_HEALTH = "amharic grade 2 health"
    AWAITING_AMHARIC_GRADE_2_MORAL = "amharic grade 2 moral"

    AWAITING_AMHARIC_GRADE_3_AMHARIC = "amharic grade 3 amharic"
    AWAITING_AMHARIC_GRADE_3_ENGLISH = "amharic grade 3 english"
    AWAITING_AMHARIC_GRADE_3_MATH = "amharic grade 3 math"
    AWAITING_AMHARIC_GRADE_3_SCIENCE = "amharic grade 3 science"
    AWAITING_AMHARIC_GRADE_3_ART = "amharic grade 3 art"
    AWAITING_AMHARIC_GRADE_3_HEALTH = "amharic grade 3 health"
    AWAITING_AMHARIC_GRADE_3_MORAL = "amharic grade 3 moral"

    AWAITING_AMHARIC_GRADE_4_AMHARIC = "amharic grade 4 amharic"
    AWAITING_AMHARIC_GRADE_4_ENGLISH = "amharic grade 4 english"
    AWAITING_AMHARIC_GRADE_4_MATH = "amharic grade 4 math"
    AWAITING_AMHARIC_GRADE_4_SCIENCE = "amharic grade 4 science"
    AWAITING_AMHARIC_GRADE_4_ART = "amharic grade 4 art"
    AWAITING_AMHARIC_GRADE_4_HEALTH = "amharic grade 4 health"
    AWAITING_AMHARIC_GRADE_4_MORAL = "amharic grade 4 moral"

    AWAITING_AMHARIC_GRADE_5_AMHARIC = "amharic grade 5 amharic"
    AWAITING_AMHARIC_GRADE_5_ENGLISH = "amharic grade 5 english"
    AWAITING_AMHARIC_GRADE_5_OROMIC = "amharic grade 5 afaan oromoo"
    AWAITING_AMHARIC_GRADE_5_MATH = "amharic grade 5 math"
    AWAITING_AMHARIC_GRADE_5_SCIENCE = "amharic grade 5 science"
    AWAITING_AMHARIC_GRADE_5_ART = "amharic grade 5 art"
    AWAITING_AMHARIC_GRADE_5_HEALTH = "amharic grade 5 health"
    AWAITING_AMHARIC_GRADE_5_MORAL = "amharic grade 5 moral"

    AWAITING_AMHARIC_GRADE_6_AMHARIC = "amharic grade 6 amharic"
    AWAITING_AMHARIC_GRADE_6_ENGLISH = "amharic grade 6 english"
    AWAITING_AMHARIC_GRADE_6_OROMIC = "amharic grade 6 afaan oromoo"
    AWAITING_AMHARIC_GRADE_6_MATH = "amharic grade 6 math"
    AWAITING_AMHARIC_GRADE_6_SCIENCE = "amharic grade 6 science"
    AWAITING_AMHARIC_GRADE_6_ART = "amharic grade 6 art"
    AWAITING_AMHARIC_GRADE_6_HEALTH = "amharic grade 6 health"
    AWAITING_AMHARIC_GRADE_6_MORAL = "amharic grade 6 moral"

    AWAITING_AMHARIC_GRADE_7_AMHARIC = "amharic grade 7 amharic"
    AWAITING_AMHARIC_GRADE_7_ENGLISH = "amharic grade 7 english"
    AWAITING_AMHARIC_GRADE_7_OROMIC = "amharic grade 7 afaan oromoo"
    AWAITING_AMHARIC_GRADE_7_MATH = "amharic grade 7 math"
    AWAITING_AMHARIC_GRADE_7_SCIENCE = "amharic grade 7 science"
    AWAITING_AMHARIC_GRADE_7_SOCIAL_STUDIES = "amharic grade 7 social studies"
    AWAITING_AMHARIC_GRADE_7_CIVICS = "amharic grade 7 civics"
    AWAITING_AMHARIC_GRADE_7_ART = "amharic grade 7 art"
    AWAITING_AMHARIC_GRADE_7_IT = "amharic grade 7 IT"
    AWAITING_AMHARIC_GRADE_7_HEALTH = "amharic grade 7 health"
    AWAITING_AMHARIC_GRADE_7_VOCATION = "amharic grade 7 vocation"

    AWAITING_AMHARIC_GRADE_8_AMHARIC = "amharic grade 8 amharic"
    AWAITING_AMHARIC_GRADE_8_ENGLISH = "amharic grade 8 english"
    AWAITING_AMHARIC_GRADE_8_OROMIC = "amharic grade 8 afaan oromoo"
    AWAITING_AMHARIC_GRADE_8_MATH = "amharic grade 8 math"
    AWAITING_AMHARIC_GRADE_8_SCIENCE = "amharic grade 8 science"
    AWAITING_AMHARIC_GRADE_8_SOCIAL_STUDIES = "amharic grade 8 social studies"
    AWAITING_AMHARIC_GRADE_8_CIVICS = "amharic grade 8 civics"
    AWAITING_AMHARIC_GRADE_8_ART = "amharic grade 8 art"
    AWAITING_AMHARIC_GRADE_8_IT = "amharic grade 8 IT"
    AWAITING_AMHARIC_GRADE_8_HEALTH = "amharic grade 8 health"
    AWAITING_AMHARIC_GRADE_8_VOCATION = "amharic grade 8 vocation"

    # Oromic grade subject states (1-8)
    AWAITING_OROMIC_GRADE_1_OROMIC = "oromic grade 1 afaan oromoo"
    AWAITING_OROMIC_GRADE_1_ENGLISH = "oromic grade 1 english"
    AWAITING_OROMIC_GRADE_1_MATH = "oromic grade 1 math"
    AWAITING_OROMIC_GRADE_1_SCIENCE = "oromic grade 1 science"
    AWAITING_OROMIC_GRADE_1_ART = "oromic grade 1 art"
    AWAITING_OROMIC_GRADE_1_HEALTH = "oromic grade 1 health"
    AWAITING_OROMIC_GRADE_1_MORAL = "oromic grade 1 moral"
    AWAITING_OROMIC_GRADE_1_GEDA = "oromic grade 1 geda"

    AWAITING_OROMIC_GRADE_2_OROMIC = "oromic grade 2 afaan oromoo"
    AWAITING_OROMIC_GRADE_2_ENGLISH = "oromic grade 2 english"
    AWAITING_OROMIC_GRADE_2_MATH = "oromic grade 2 math"
    AWAITING_OROMIC_GRADE_2_SCIENCE = "oromic grade 2 science"
    AWAITING_OROMIC_GRADE_2_ART = "oromic grade 2 art"
    AWAITING_OROMIC_GRADE_2_HEALTH = "oromic grade 2 health"
    AWAITING_OROMIC_GRADE_2_MORAL = "oromic grade 2 moral"
    AWAITING_OROMIC_GRADE_2_GEDA = "oromic grade 2 geda"

    AWAITING_OROMIC_GRADE_3_OROMIC = "oromic grade 3 afaan oromoo"
    AWAITING_OROMIC_GRADE_3_ENGLISH = "oromic grade 3 english"
    AWAITING_OROMIC_GRADE_3_MATH = "oromic grade 3 math"
    AWAITING_OROMIC_GRADE_3_SCIENCE = "oromic grade 3 science"
    AWAITING_OROMIC_GRADE_3_ART = "oromic grade 3 art"
    AWAITING_OROMIC_GRADE_3_HEALTH = "oromic grade 3 health"
    AWAITING_OROMIC_GRADE_3_MORAL = "oromic grade 3 moral"
    AWAITING_OROMIC_GRADE_3_GEDA = "oromic grade 3 geda"

    AWAITING_OROMIC_GRADE_4_OROMIC = "oromic grade 4 afaan oromoo"
    AWAITING_OROMIC_GRADE_4_ENGLISH = "oromic grade 4 english"
    AWAITING_OROMIC_GRADE_4_MATH = "oromic grade 4 math"
    AWAITING_OROMIC_GRADE_4_SCIENCE = "oromic grade 4 science"
    AWAITING_OROMIC_GRADE_4_ART = "oromic grade 4 art"
    AWAITING_OROMIC_GRADE_4_HEALTH = "oromic grade 4 health"
    AWAITING_OROMIC_GRADE_4_MORAL = "oromic grade 4 moral"
    AWAITING_OROMIC_GRADE_4_GEDA = "oromic grade 4 geda"

    AWAITING_OROMIC_GRADE_5_OROMIC = "oromic grade 5 afaan oromoo"
    AWAITING_OROMIC_GRADE_5_ENGLISH = "oromic grade 5 english"
    AWAITING_OROMIC_GRADE_5_AMHARIC = "oromic grade 5 amharic"
    AWAITING_OROMIC_GRADE_5_MATH = "oromic grade 5 math"
    AWAITING_OROMIC_GRADE_5_SCIENCE = "oromic grade 5 science"
    AWAITING_OROMIC_GRADE_5_ART = "oromic grade 5 art"
    AWAITING_OROMIC_GRADE_5_HEALTH = "oromic grade 5 health"
    AWAITING_OROMIC_GRADE_5_MORAL = "oromic grade 5 moral"
    AWAITING_OROMIC_GRADE_5_GEDA = "oromic grade 5 geda"

    AWAITING_OROMIC_GRADE_6_OROMIC = "oromic grade 6 afaan oromoo"
    AWAITING_OROMIC_GRADE_6_ENGLISH = "oromic grade 6 english"
    AWAITING_OROMIC_GRADE_6_AMHARIC = "oromic grade 6 amharic"
    AWAITING_OROMIC_GRADE_6_MATH = "oromic grade 6 math"
    AWAITING_OROMIC_GRADE_6_SCIENCE = "oromic grade 6 science"
    AWAITING_OROMIC_GRADE_6_ART = "oromic grade 6 art"
    AWAITING_OROMIC_GRADE_6_HEALTH = "oromic grade 6 health"
    AWAITING_OROMIC_GRADE_6_MORAL = "oromic grade 6 moral"
    AWAITING_OROMIC_GRADE_6_GEDA = "oromic grade 6 geda"

    AWAITING_OROMIC_GRADE_7_OROMIC = "oromic grade 7 afaan oromoo"
    AWAITING_OROMIC_GRADE_7_ENGLISH = "oromic grade 7 english"
    AWAITING_OROMIC_GRADE_7_AMHARIC = "oromic grade 7 amharic"
    AWAITING_OROMIC_GRADE_7_MATH = "oromic grade 7 math"
    AWAITING_OROMIC_GRADE_7_SCIENCE = "oromic grade 7 science"
    AWAITING_OROMIC_GRADE_7_SOCIAL_STUDIES = "oromic grade 7 social studies"
    AWAITING_OROMIC_GRADE_7_CIVICS = "oromic grade 7 civics"
    AWAITING_OROMIC_GRADE_7_ART = "oromic grade 7 art"
    AWAITING_OROMIC_GRADE_7_IT = "oromic grade 7 IT"
    AWAITING_OROMIC_GRADE_7_HEALTH = "oromic grade 7 health"
    AWAITING_OROMIC_GRADE_7_VOCATION = "oromic grade 7 vocation"
    AWAITING_OROMIC_GRADE_7_GEDA = "oromic grade 7 geda"

    AWAITING_OROMIC_GRADE_8_OROMIC = "oromic grade 8 afaan oromoo"
    AWAITING_OROMIC_GRADE_8_ENGLISH = "oromic grade 8 english"
    AWAITING_OROMIC_GRADE_8_AMHARIC = "oromic grade 8 amharic"
    AWAITING_OROMIC_GRADE_8_MATH = "oromic grade 8 math"
    AWAITING_OROMIC_GRADE_8_SCIENCE = "oromic grade 8 science"
    AWAITING_OROMIC_GRADE_8_SOCIAL_STUDIES = "oromic grade 8 social studies"
    AWAITING_OROMIC_GRADE_8_CIVICS = "oromic grade 8 civics"
    AWAITING_OROMIC_GRADE_8_ART = "oromic grade 8 art"
    AWAITING_OROMIC_GRADE_8_IT = "oromic grade 8 IT"
    AWAITING_OROMIC_GRADE_8_HEALTH = "oromic grade 8 health"
    AWAITING_OROMIC_GRADE_8_VOCATION = "oromic grade 8 vocation"
    AWAITING_OROMIC_GRADE_8_GEDA = "oromic grade 8 geda"
        

